### PR TITLE
Migrate to k8s.io/klog from glog.

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
@xing-yang the test fail with below error:

```
$ go version
go version go1.10.3 linux/amd64
go.env
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/travis/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/travis/gopath"
GORACE=""
GOROOT="/home/travis/.gimme/versions/go1.10.3.linux.amd64"
GOTMPDIR=""
GOTOOLDIR="/home/travis/.gimme/versions/go1.10.3.linux.amd64/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build655073999=/tmp/go-build -gno-record-gcc-switches"
Using Go 1.5 Vendoring, not checking for Godeps
install
Makefile detected
0.75s$ go fmt $(go list ./... | grep -v vendor) | wc -l | grep 0
The command "go fmt $(go list ./... | grep -v vendor) | wc -l | grep 0" exited with 1.
```

Where it run successfully for me with Go version 1.11

```
[root@localhost external-snapshotter]# go fmt $(go list ./... | grep -v vendor) | wc -l | grep 0
0
[root@localhost external-snapshotter]# git status
On branch klog
nothing to commit, working tree clean
[root@localhost external-snapshotter]# go version
go version go1.11.1 linux/amd64
[root@localhost external-snapshotter]# 

```

**Comment by xing-yang** [comment]
@humblec The go version here is a little old.  There is a PR that updates the go version to 1.11.1: https://github.com/kubernetes-csi/external-snapshotter/pull/86.  We can merge your PR after that one.  Thanks.

**Comment by humblec** [comment]
@xing-yang sure. I will wait for the same.

**Comment by humblec** [comment]
@xing-yang the mentioned PR is merged now, can we continue reviewing this PR ?

**Comment by jsafrane** [comment]
@xing-yang @humblec, we need klog for PR #97. It does not matter in which order are the PRs merged, just csi-lib-utils/rpc will log to klog and nobody will see it until this PR is merged.

**Comment by xing-yang** [comment]
This looks okay, but need a rebase.  @humblec can you please rebase?  Thanks.

**Comment by xing-yang** [comment]
Hi @humblec , can you please rebase this PR to include klog changes only?  Pruning of unused dependencies is done in this PR: https://github.com/kubernetes-csi/external-snapshotter/pull/99.  I'll merge your PR once rebase is done.  Thanks.

**Comment by humblec** [comment]
@xing-yang was on sick leave , so the delay. I will rebase this PR soon.

**Comment by humblec** [comment]
@xing-yang forgot to ping you .. here it is .

**Comment by xing-yang** [comment]
There is still usage of glog in external-snapshotter/cmd/csi-snapshotter/create_crd.go.

**Comment by humblec** [comment]
@xing-yang done. PTAL :)

**Pull request merged**
