### PR TITLE
Add support for snapshotting migrated in-tree volumes

### PR DESCRIPTION
**Pull request by mitchellhuang**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
* Add support for snapshotting in-tree volumes migrated by CSIMigration feature-gate in Kubernetes
* Maintain support for existing native CSI volumes
* Use csi-translation-lib for translation https://github.com/kubernetes/csi-translation-lib

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes-csi/external-snapshotter/issues/489

**Special notes for your reviewer**:
n/a

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by xing-yang** [comment]
Hi @mitchellhuang, CSI migration is intended to support features that are already supported by in-tree drivers. It is not intended to add new CSI features.

**Comment by renan** [comment]
Any progress on this?

It would awesome to have this feature after having migrated a bunch of volumes to CSI and not really wanting to recreate those volumes, maybe even having downtime.

**Comment by xing-yang** [comment]
There's no change here. CSI migration is intended to support features that are already supported by in-tree drivers. It is not intended to add new CSI features.

**Comment by renan** [comment]
> When a Kubernetes cluster administrator updates a cluster to enable CSI migration, existing stateful deployments and workloads continue to function as they always have; however, behind the scenes Kubernetes hands control of all storage management operations (previously targeting in-tree drivers) to CSI drivers.
> https://kubernetes.io/blog/2019/12/09/kubernetes-1-17-feature-csi-migration-beta/#what-is-csi-migration

As I understood, once a volume has been migrated to a CSI driver the volume should be treated as a CSI volume. Hence it should be possible to create snapshots for it since it is now backed up by a CSI driver. Am I missing something?

**Comment by xing-yang** [comment]
See this new blog on CSI migration. It specifically calls out that new CSI features such as volume snapshotting is not supported for CSI migrated volumes.
https://kubernetes.io/blog/2021/12/10/storage-in-tree-to-csi-migration-status-update/#what-should-i-do-as-a-user

**Comment by renan** [comment]
That clarifies things. Thank you!

**Comment by humblec** [comment]
@mitchellhuang @xing-yang  yeah, I was also in an impression that we could support this functionality. The reason being many volumes are migrated and also the user get the choice to stick or use new CSI SC based on their requirement. so, appreciated if we could revalidate about this..  :+1:

**Comment by msau42** [comment]
CSI migration is intended as a way to provide backwards compatibility for the intree  API when we remove the built-in cloud providers. It was not meant to provide forward compatibility to new features.

I understand how convenient it would be to not have to recreate volumes using the CSI API to get CSI functionality, but I also worry about the precedent this will set and additional burden this is going to place on all storage feature developers and maintainers of the intree plugins if every single feature we develop in the future needs to be designed, implemented, tested, and supported to handle csi migration.

**Pull request closed without merging**
