### PR TITLE
Add latest release-tools to release-4.0 branch

### PR DESCRIPTION
**Pull request by ggriffiths**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Updates release-tools

**Which issue(s) this PR fixes**:
n/a

**Special notes for your reviewer**:
n/a

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

Squashed 'release-tools/' changes from 3b6d17b..bc0504ad

bc0504ad Merge pull request #140 from jsafrane/remove-unused-k8s-libs
5b1de1ad go-get-kubernetes.sh: remove unused k8s libs
49b42693 Merge pull request #120 from pohly/add-kubernetes-release
a1e11275 Merge pull request #139 from pohly/kind-for-kubernetes-latest
1c0fb096 prow.sh: use KinD main for latest Kubernetes
1d77cfcb Merge pull request #138 from pohly/kind-update-0.10
bff2fb7e prow.sh: KinD 0.10.0
95eac336 Merge pull request #137 from pohly/fix-go-version-check
437e4311 verify-go-version.sh: fix check after removal of travis.yml
1748b16b Merge pull request #136 from pohly/go-1.16
ec844ea6 remove travis.yml, Go 1.16
df76aba8 Merge pull request #134 from andyzhangx/add-build-arg
e314a56d add build-arg ARCH for building multi-arch images, e.g. ARG ARCH FROM k8s.gcr.io/build-image/debian-base-${ARCH}:v2.1.3
7bc70e52 Merge pull request #129 from pohly/squash-documentation
e0b02e72 README.md: document usage of --squash
316cb957 Merge pull request #132 from yiyang5055/bugfix/boilerplate
26e2ab10 fix: default boilerplate path
1add8c18 Merge pull request #133 from pohly/kubernetes-1.20-tag
3e811d6c prow.sh: fix "on-master" prow jobs
1d60e779 Merge pull request #131 from pohly/kubernetes-1.20-tag
9f104590 prow.sh: support building Kubernetes for a specific version
f7e7ee49 docs: steps for adding testing against new Kubernetes release
fe1f2848 Merge pull request #121 from kvaps/namespace-check
8fdf0f78 Merge pull request #128 from fengzixu/master
1c94220d fix: fix a bug of csi-sanity
a4c41e6a Merge pull request #127 from pohly/fix-boilerplate
ece0f50 check namespace for snapshot-controller
dbd89672 verify-boilerplate.sh: fix path to script
9289fd16 Merge pull request #125 from sachinkumarsingh092/optional-spelling-boilerplate-checks
ad29307f Make the spelling and boilerplate checks optional
5f06d024 Merge pull request #124 from sachinkumarsingh092/fix-spellcheck-boilerplate-tests
48186eba Fix spelling and boilerplate errors
71690aff Merge pull request #122 from sachinkumarsingh092/include-spellcheck-boilerplate-tests
981be3fe Adding spelling and boilerplate checks.
2bb75253 Merge pull request #117 from fengzixu/master
4ab8b154 use the tag to replace commit of csi-test
5d74e455 change the csi-test import path to v4
7dcd0a99 upgrade csi-test to v4.0.2

git-subtree-dir: release-tools
git-subtree-split: bc0504ad76ac6e20d0d7c60d46f62c7ff7591f8c

### CODE REVIEW

**Comment by xing-yang** [comment]
Can you add the following commit message to your PR description?
https://github.com/kubernetes-csi/external-snapshotter/pull/498/commits/4683101b9e82793d9685a74b758acce55e19b8a9

**Comment by ggriffiths** [comment]
Added

**Pull request merged**
