### PR TITLE
Upgrade csi-lib-utils to 0.8.1

### PR DESCRIPTION
**Pull request by Jiawei0227**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Upgrade csi-lib-utils to version 0.8.1

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
Cherry-pick from https://github.com/kubernetes-csi/external-snapshotter/pull/387. Add `process_start_time_seconds` metric so that we can properly extrapolate the beginning part of the histogram data.
```

### CODE REVIEW

**Comment by xing-yang** [comment]
@Jiawei0227 what is the difference between this PR and this other PR that is already merged?  https://github.com/kubernetes-csi/external-snapshotter/pull/387

**Comment by xing-yang** [comment]
I see.  Looks like https://github.com/kubernetes-csi/external-snapshotter/pull/387 is a commit to the master while this one commits to release-3.0.

So this one should be a cherry-pick then.

**Comment by xing-yang** [comment]
By the way, this is actually a new feature.  We should not be cherry-picking new features into a stable branch.

/hold

**Comment by msau42** [comment]
This is actually a bug fix. Without this process_start_time metric, we cannot properly extrapolate the beginning part of the histogram data.

**Pull request merged**
