### PR TITLE
Change OWNERS_ALIASES to a symlink

### PR DESCRIPTION
**Pull request by xing-yang**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Change OWNERS_ALIASES to a symlink to release-tools/KUBERNETES_CSI_OWNERS_ALIASES
so that aliases can be recognized by CI.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
Without this change, no one in `kubernetes-csi-approvers` can approve a PR in release-4.0 branch.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by xing-yang** [comment]
@yuxiangqian No one on `kubernetes-csi-approvers` can approve a PR in release-4.0 now.  Can you approve this?  Thanks.

**Review by yuxiangqian — APPROVED** [review]
/lgtm /approve

**Pull request merged**
