### PR TITLE
Cherry-pick: Check if ListSnapshots is supported during GetSnapshotStatus

### PR DESCRIPTION
**Pull request by hakanmemisoglu**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
Cherry-picks a fix where external snaphotter fails in prebound snapshot case with a driver
that does not support `ListSnapshots` request.
Release 1.2 doesn't have the fix in the master. 

**Special notes for your reviewer**:

This is a cherry-pick from master.

**Does this PR introduce a user-facing change?**:

```release-note
Cherry picks PR #138: Prebound snapshots will work correctly with CSI drivers that does not support ListSnasphots.
```

### CODE REVIEW

**Comment by hakanmemisoglu** [comment]
Does this repo have something similar: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md

**Comment by xing-yang** [comment]
No, we don't have a cherry-pick script.

**Pull request merged**
