### PR TITLE
update setup-csi-snapshotter.yaml csi-snapshotter image 

### PR DESCRIPTION
**Pull request by f10atin9**
update setup-csi-snapshotter.yaml csi-snapshotter image from v4.0.0 to v4.1.1

### CODE REVIEW

**Comment by xing-yang** [comment]
Please sign CLA.

**Comment by xing-yang** [comment]
Can you update this image too?
https://github.com/kubernetes-csi/external-snapshotter/blob/master/deploy/kubernetes/webhook-example/webhook.yaml#L20

**Comment by f10atin9** [comment]
Ok i updated it.

**Comment by xing-yang** [comment]
@f10atin9, please sign CLA.

**Comment by f10atin9** [comment]
@xing-yang Okay, I have signed the CLA

**Pull request merged**
