### PR TITLE
update kube dependencies to v1.24.0 release

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

/kind api-change

-->
```release-note
Kube client dependencies are updated to v1.24.0
```

### CODE REVIEW

**Comment by pohly** [comment]
How is this an API change?

**Comment by humblec** [comment]
> How is this an API change?

@pohly my understanding was that, considering the API client is upgraded to latest version we tag it with `api-change` , if its not correct, please point out the correct label. :)

**Review by pohly — APPROVED** [review]
/lgtm

**Comment by pohly** [comment]
/assign @xing-yang 

For approval.

**Comment by xing-yang** [comment]
Please backport to release-6.0 branch.

**Pull request merged**
