### PR TITLE
replace "dep" with "go mod"

### PR DESCRIPTION
**Pull request by pohly**
```release-note
Migrated to Go modules, so the source builds also outside of GOPATH.
```

### CODE REVIEW

**Comment by xing-yang** [comment]
I'd like to push this PR on hold until the snapshot beta PR is merged: https://github.com/kubernetes-csi/external-snapshotter/pull/139

**Comment by xing-yang** [comment]
@pohly can you rebase?  we can get this merged.

**Comment by pohly** [comment]
Xing Yang <notifications@github.com> writes:
> @pohly can you rebase?  we can get this merged.

I updated the PR by re-running "go mod init && go mod tidy && go mod
vendor".

**Pull request merged**
