### PR TITLE
Allow csi-snapshotter to create and manage VolumeSnapshots

### PR DESCRIPTION
**Pull request by leonardoce**
This patch allows the `external-snapshotter-runner` ClusterRole, bound to the `csi-snapshotter` Service Account, to create and manage VolumeSnapshot objects.

This is needed during the synchronization of VolumeGroupSnapshots.

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

We need this permission to reconcile VolumeGroupSnapshot objects, which in turn will create VolumeSnapshot and VolumeSnapshotContent resources.

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NONE

### CODE REVIEW

**Comment by xing-yang** [comment]
Can you rebase? The CVE reported by Trivy scan should be already fixed in the master branch:

https://github.com/kubernetes-csi/external-snapshotter/blob/master/go.mod#L57
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc v0.41.0

**Comment by xing-yang** [comment]
This PR is merged and fixed the Trivy issue: https://github.com/kubernetes-csi/external-snapshotter/pull/962.  Can you rebase?

**Comment by leonardoce** [comment]
Done @xing-yang. Thank you!

**Comment by xing-yang** [comment]
/lgtm
/approve

Thanks @leonardoce !

**Pull request merged**
