### PR TITLE
Cherrypick #653 to release-5.0 branch

### PR DESCRIPTION
**Pull request by Jainbrt**
Signed-off-by: Abhishek Jain <abjain39@in.ibm.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change

kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Cherrypick #653: Change snapshot controller image version to 5.0.1
```

### CODE REVIEW

**Comment by Jainbrt** [comment]
@xing-yang Could you please have a look at this ?

**Comment by xing-yang** [comment]
Can you set the "Type of PR" in PR description?

**Comment by Jainbrt** [comment]
> Can you set the "Type of PR" in PR description?

Done @xing-yang

**Pull request merged**
