### PR TITLE
Add snapshot CRD API reference doc for the repo.

### LINKED ISSUE #102: Generating CRD API docs
Consider using this tool: https://github.com/ahmetb/gen-crd-api-reference-docs/

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

Fix #102 
-->
```release-note

```

### CODE REVIEW

**Comment by humblec** [comment]
@xing-yang @yuxiangqian first version of our documentation :+1:

**Comment by xing-yang** [comment]
Can you add steps in hack/README to describe how you generated this doc and also how to view it?

**Comment by humblec** [comment]
> Can you add steps in hack/README to describe how you generated this doc and also how to view it?

@xing-yang see it here https://htmlpreview.github.io/?https://github.com/humblec/external-snapshotter/blob/crd-doc/docs/docs.html

**Comment by humblec** [comment]
> > Can you add steps in hack/README to describe how you generated this doc and also how to view it?
> 
> @xing-yang see it here https://htmlpreview.github.io/?https://github.com/humblec/external-snapshotter/blob/crd-doc/docs/docs.html

Regarding: how this was generated, it's using the  tool mentioned #102 , and on documentation, I doubt we could do that unless we import above mentioned tool to our repo and instruct on how to generate. The only reason to regenrate this doc would be when there is a change in the CRD I believe.

**Comment by yuxiangqian** [comment]
It seems generated docs are not very common in K8s repos, and having it introduces more places which could need to be sync'd with API definition. I am not  sure we need it here.

**Comment by humblec** [comment]
> It seems generated docs are not very common in K8s repos, and having it introduces more places which could need to be sync'd with API definition. I am not sure we need it here.

@yuxiangqian this is to fix #102 opened by @msau42 .. Updated the PR description.

**Comment by yuxiangqian** [comment]
Sure, what I mean is that it does not seem to be appropriate to me that the generated doc sits inside of the repo as its normally connected with API version. Having it sits in the folder created in this PR is not a proper choice to me.

**Comment by humblec** [comment]
> Sure, what I mean is that it does not seem to be appropriate that the generated doc sits inside of the repo as its normally connected with a specific API version. Having it sits in the folder created in this PR is not a proper choice to me.

@xing-yang @msau42 can you please share your thought too ? I followed the exact process mentioned in the issue description, but if thats not what we want please let me know.

**Comment by msau42** [comment]
/reopen

I think that it's good to have an API reference for these CRDs. Maybe https://kubernetes-csi.github.io/ would be a good place to put it

**Comment by xing-yang** [comment]
@humblec can you move this PR to  https://kubernetes-csi.github.io/?

**Pull request closed without merging**
