### PR TITLE
Update images

### PR DESCRIPTION
**Pull request by xing-yang**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This PR updates images for external-snapshotter and external-provisioner in the master.

**Which issue(s) this PR fixes**:
The existing images in the deployment yaml file is out of date.

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by jingxu97** [comment]
@xing-yang did you make any changes?

**Comment by xing-yang** [comment]
@jingxu97 I only rebased it because the Travis CI is hanging.  However CI still hangs after I rebased it.  
@msau42 Do you have any idea why the Travis CI stays in Pending state forever?

**Comment by msau42** [comment]
I vaguely remember there was some announcement regarding travis changing their events api and prow no longer supporting it.  So it should not be a blocking job anymore.  Is it preventing merge?

**Comment by xing-yang** [comment]
@msau42 Yes, it prevents merging.

**Comment by msau42** [comment]
I've disabled pull request building in travis.  You might need to close and reopen the pr

**Comment by msau42** [comment]
Or maybe open a new pr...

**Comment by xing-yang** [comment]
Submitted another PR: https://github.com/kubernetes-csi/external-snapshotter/pull/170.
Closing this one.

**Pull request closed without merging**
