### PR TITLE
update kube and dependencies to v1.23

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

/kind cleanup

-->
```release-note
NONE
```

### CODE REVIEW

**Comment by humblec** [comment]
/assign @xing-yang 

This is the backport of #627

**Comment by xing-yang** [comment]
This looks like a new commit rather than a cherry-pick.

**Comment by humblec** [comment]
> This looks like a new commit rather than a cherry-pick.

@xing-yang it was a cherry-pick , however current version should be the one you are looking for :)  . ptal.. thanks !

**Comment by xing-yang** [comment]
This is not a feature.  You can probably say "cleanup".

**Comment by humblec** [comment]
> This is not a feature. You can probably say "/kind cleanup".

@xing-yang sure, updated that .

**Pull request merged**
