### PR TITLE
Lift kube dependency to v0.18.2

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by xing-yang** [comment]
Is there any specific reason that v0.18.2 is required?

**Comment by humblec** [comment]
> Is there any specific reason that v0.18.2 is required?

@xing-yang the controller gen v0.3.0 internally bumped its dependencies to `v0.18.2` (#311 ). That's why I thought its good to update the dependencies to `1.18.2` to be in parity.

**Comment by humblec** [comment]
Closing this one for now @xing-yang as I see couple of duplicate PRs  on upgrading the dep. :) .. May be next time onwards we have to keep single issue and assignee :)

**Comment by xing-yang** [comment]
No issue was ever opened for this and we have never assigned this task to anyone, but we have several volunteers submitting PRs:).  Thanks!

**Pull request closed without merging**
