### PR TITLE
change image pullpolicy from Always to IfNotPresent

### PR DESCRIPTION
**Pull request by Madhu-1**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

 /kind cleanup

> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

currently, image pull policy is set to Always, if the pod restarts the image will be always pulled even if its present, changing
the pull policy will speed up the pod creation.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Comment by xing-yang** [comment]
I think our hostpath CSI driver deployment scripts all use "Always" to make sure the image is the latest.  So we should be consistent here.
Deployment files in this repo are examples.  If you really need "IfNotPresent" for your production deployment, please keep your own copy of yaml files.

**Comment by Madhu-1** [comment]
Even the external-provisioner deployment https://github.com/kubernetes-csi/external-provisioner/blob/321fa5c1c951f1446a91789792c25220fe1c1840/deploy/kubernetes/deployment.yaml#L29 is also set to IfNotPresent

**Comment by xing-yang** [comment]
We now actually need to use "IfNotPresent" to deploy snapshot-controller using a local image in prow.sh.  So I'm going to merge this.

Thanks!

**Pull request merged**
