### PR TITLE
Bump go version to 1.15

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by xing-yang** [comment]
Please rebase.

**Comment by humblec** [comment]
@xing-yang rebased .. ptal .. thanks!

**Comment by xing-yang** [comment]
Looks like you need to do a "go mod vendor".

**Comment by humblec** [comment]
> Looks like you need to do a "go mod vendor".

@xing-yang I had to rebase to master. Did that again :).. PTAL . Thanks

**Pull request merged**
