### PR TITLE
Merge pull request #588 from Kartik494/ValidateWebhook

### PR DESCRIPTION
**Pull request by Kartik494**
Backported #588 

```release-note
Cherry-pick #588: Updated `CertificateSigningRequest apiversion` to `V1`
```

### CODE REVIEW

**Comment by Kartik494** [comment]
@xing-yang submitted this PR in reference for the [follow up](https://github.com/kubernetes-csi/external-snapshotter/pull/588#issuecomment-972065591) .

**Comment by xing-yang** [comment]
Can you add a release note?

**Comment by Kartik494** [comment]
@xing-yang Added the release note for the same.PTAL

**Pull request merged**
