### PR TITLE
WIP: Test - Do not merge

### PR DESCRIPTION
**Pull request by xing-yang**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by xing-yang** [comment]
@pohly Any idea why the `kubernetes-csi-approvers` alias does not work in release-4.0 branch?

**Comment by pohly** [comment]
>  Any idea why the `kubernetes-csi-approvers` alias does not work in release-4.0 branch?

In which way is it not working?

**Comment by pohly** [comment]
> > Any idea why the `kubernetes-csi-approvers` alias does not work in release-4.0 branch?
> 
> In which way is it not working?

Never mind, I think I see what's wrong - see https://github.com/kubernetes-csi/external-snapshotter/commit/076a2129078a9185eb27999c0ebd29bfa6fc753e#r54318325

**Comment by msau42** [comment]
https://github.com/kubernetes-csi/external-snapshotter/pull/568

**Pull request closed without merging**
