### PR TITLE
Allow resync on VolumeSnapshotContent when there is no error from CreateSnapshot

### LINKED ISSUE #533: external-snapshotter constantly retrying CreateSnapshot calls on error w/o backoff
Creating a snapshot from a non-existing volume will repro this. @jsafrane discovered this, opening this issue for tracking.

### PR DESCRIPTION
**Pull request by pwschuurman**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
After creating a snapshot, external-snapshotter needs to wait for a VolumeSnapshotContent to be ready. This re-adds logic (removed in #651) to enqueue a VolumeSnapshotContent after it has been updated, as long as there wasn't an error encountered in creating (or updating) the snapshot. Effectively this allows the controller to continuously poll the VolumeSnapshotContent until it is ready.
Fixes #533 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
Ensure that the CSI snapshotter sidecar allows for CreateSnapshot retries while waiting for a snapshot to be ready.
```

### CODE REVIEW

**Comment by xing-yang** [comment]
@pwschuurman Can you add a release note?  Have you tested this fix with those PD CSI driver tests that failed previously?

**Comment by pwschuurman** [comment]
Updated the release note. I have tested this fix with the PD CSI driver tests, and this update fixes them.

**Pull request merged**
