### PR TITLE
release-3.0: Update release tools

### PR DESCRIPTION
**Pull request by ggriffiths**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Updates this branch to latest rel tools

**Which issue(s) this PR fixes**:
n/a

**Special notes for your reviewer**:
n/a

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by ggriffiths** [comment]
Includes all changes from release-tools master up until commit 5d874cce4e649dfd254d01b9b44179ffa72aee75.

The latest release tools were failing on this branch: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-csi_external-snapshotter/436/pull-kubernetes-csi-external-snapshotter-1-19-on-kubernetes-1-19/1334383791833092096

**Comment by pohly** [comment]
> The latest release tools were failing on this branch

This needs to be fixed. We can't be stuck on a non-recent csi-release-tools.

**Comment by xing-yang** [comment]
@ggriffiths we need to squash the commits.  Can you try this script: https://github.com/kubernetes-csi/csi-release-tools/issues/7#issuecomment-707025402

**Comment by ggriffiths** [comment]
Ok, I've reopened a new PR with the script - had issues pushing directly to this branch and it was closed.
https://github.com/kubernetes-csi/external-snapshotter/pull/437

**Pull request closed without merging**
