### PR TITLE
Change snapshot controller image version to 6.2.2 in release-6.2 branch

### PR DESCRIPTION
**Pull request by Jainbrt**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change

 /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Comment by xing-yang** [comment]
/ok-to-test

Can you add a kind in the PR description?

**Comment by Jainbrt** [comment]
@xing-yang can you please help to get this merged ?

**Comment by Jainbrt** [comment]
@xing-yang can you please help as above test is failing?

**Comment by xing-yang** [comment]
There's an issue opened for this: https://github.com/kubernetes/kubernetes/issues/120997

**Comment by Jainbrt** [comment]
@xing-yang Thanks for retesting. can you please help put lgtm label too?

**Pull request merged**
