### PR TITLE
feat: Add migrated label to metrics

### PR DESCRIPTION
**Pull request by nearora-msft**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
/kind feature
> /kind flake

**What this PR does / why we need it**:
his PR is an extension to kubernetes-csi/csi-lib-utils#77 to send "migrated" label in the metrics

**Which issue(s) this PR fixes**:

Fixes #
Partially Addressed # kubernetes/kubernetes#98279

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Set the value of "migrated" field in the metrics to true or false to indicate if the call is a migration enabled feature or not
```

### CODE REVIEW

**Comment by nearora-msft** [comment]
@Jiawei0227 Could you please look at this draft PR to see if things looks ok?

**Comment by xing-yang** [comment]
@Jiawei0227 Is this PR needed?  Snapshot is not supported by in-tree plugins.

**Comment by nearora-msft** [comment]
> @Jiawei0227 Is this PR needed? Snapshot is not supported by in-tree plugins.

Oh is that so? I will close this then.

**Comment by Jiawei0227** [comment]
Yep, we do not need to add this for snapshot. Only the other three sidecars

**Pull request closed without merging**
