### PR TITLE
[release-7.0]: Fix logging in the volumegroupsnapshot methods

### PR DESCRIPTION
**Pull request by Madhu-1**
This is the backport of https://github.com/kubernetes-csi/external-snapshotter/pull/1014 

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup

> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Cherry-pick from PR [#1014](https://github.com/kubernetes-csi/external-snapshotter/pull/1014)
```

### CODE REVIEW

**Comment by xing-yang** [comment]
Can you add release note to all the cherry-pick PRs similar to this one: https://github.com/kubernetes-csi/external-snapshotter/pull/1006

**Comment by Madhu-1** [comment]
@xing-yang added it, PTAL. Thank you

**Pull request merged**
