### PR TITLE
release-2.1: Update release tools for go build fix

### LINKED ISSUE #385: Fix go 1.15 install issue in release-2.1
As seen in https://github.com/kubernetes-csi/external-snapshotter/pull/384

and originally https://github.com/kubernetes-csi/external-snapshotter/pull/348, release-2.1 PR jobs are failing with `ERROR: installation of Go 1.15.0 failed`.

Looking into this now.

### PR DESCRIPTION
**Pull request by ggriffiths**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Updates the release tools to latest upstream

**Which issue(s) this PR fixes**:
Fixes #385 

**Special notes for your reviewer**:
n/a

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by ggriffiths** [comment]
This fixed the build error mentioned in #385, but for some reason the jobs are failing to pull a few images.

**Comment by ggriffiths** [comment]
I think I found the problem. Latest release tools uses the new staging registry:
https://github.com/kubernetes-csi/csi-release-tools/commit/e73c2ce5312662816b180c5b03eb490322051fd7

but, some of the images below are not there:
1. gcr.io/k8s-staging-sig-storage/csi-attacher:v3.0.0-rc1
2. gcr.io/k8s-staging-sig-storage/hostpathplugin:v1.4.0-rc2

I'm updating the release-tools here to a few commits before that to unblock PRs to external-snapshotter:release-2.1.

cc @xing-yang @msau42

**Comment by msau42** [comment]
I think what needs to happen is to release a new 1.4.1 of the hostpath driver with updated sidecars, and then we update gen-jobs in test-infra to use 1.4.1: https://github.com/kubernetes/test-infra/pull/19280/files#diff-96340ecad23cb8abd9aa581e9b2864ecR47. I can work on that next week.

In the meantime, updating release tools to before this commit is fine.

**Comment by ggriffiths** [comment]
That sounds good! I can help with those updates as well.

**Comment by xing-yang** [comment]
This looks good to me.

@ggriffiths @msau42 anything else needs to be addressed in this PR before merging?

**Comment by msau42** [comment]
/lgtm
/approve

We'll address the remaining items as a followup

**Pull request merged**
