### PR TITLE
Update kubernetes dependency to 1.13.2 from 1.13.alpha release.

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
@xing-yang PTAL  :)

**Comment by xing-yang** [comment]
@humblec because external-provisioner has a dependency on external-snapshotter, we usually coordinate the update of dependencies between them.

**Comment by xing-yang** [comment]
external-snapshotter now depends on k8s 1.14: https://github.com/kubernetes-csi/external-snapshotter/pull/105

I'm going to close this PR.  Thanks @humblec for working on it!

**Pull request closed without merging**
