### PR TITLE
remove storage class permissions from snapshot controller cluster role

### LINKED ISSUE #644: snapshot-controller shouldn't require read permissions for storage class resources
As part of deploying snapshot controller in our K8s cluster, we were reviewing rbac permissions required by controller and noticed that [storage class read permissions](https://github.com/kubernetes-csi/external-snapshotter/blob/ea7834929a37af7af5b63a979001cdddc0372f4e/deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml#L27) are mentioned in [deployment recipes](https://github.com/kubernetes-csi/external-snapshotter/tree/master/deploy/kubernetes) provided. I don't see any references of storage class resource being used in this repository. May be we can remove it from deployment recipes if it is not required or let me know if any workflow exists in external csi snapshotter requiring these read permissions.

### PR DESCRIPTION
**Pull request by iyashu**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup

> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
PR to remove redundant storage class permissions from snapshot controller deployment recipes.

**Which issue(s) this PR fixes**:

Fixes #644 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
remove unnecessary rbac read permissions of storage class resources from snapshot controller deployment
```

### CODE REVIEW

**Comment by xing-yang** [comment]
Can you add a release note?

**Comment by xing-yang** [comment]
The release note says "remove redundant rbac read permissions of storage class resources...".  Is it redundant or unnecessary?

**Comment by iyashu** [comment]
I think they used to be required perms, but now they no longer needed (hence used `redundant` :P ). I've updated the pull request description with `unnecessary` since both sounds equivalent to me.

**Comment by xing-yang** [comment]
cc @lintongj @deepakkinni

**Pull request merged**
