### PR TITLE
Update release-1.2 to use csi-snapshotter v1.2.2

### PR DESCRIPTION
**Pull request by ggriffiths**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
updates release-1.2 branch to use the latest 1.2.x image, v1.2.2.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
v1.2.2 is not yet on gcr.io, unless the image name changed for 1.x on gcr.io?
```
~ docker pull k8s.gcr.io/sig-storage/csi-snapshotter:v1.2.2


Error response from daemon: manifest for k8s.gcr.io/sig-storage/csi-snapshotter:v1.2.2 not found
```

**Does this PR introduce a user-facing change?**
```release-note
NONE
```

### CODE REVIEW

**Comment by xing-yang** [comment]
@ggriffiths Those older images are not uploaded to the new repo yet.  I'll need to upload them.

**Comment by ggriffiths** [comment]
Sounds good @xing-yang, I can wait on these PRs until that is done.

**Comment by xing-yang** [comment]
@ggriffiths I've uploaded the image.  Can you check if you can pull image from the new repo now?

**Comment by ggriffiths** [comment]
Yeah, I was able to pull the images @xing-yang . Updated this PR and the release-1.1 one.

**Comment by ggriffiths** [comment]
This branch needs the latest release-tools, but the latest subtree requires go modules. Closing for now.

**Pull request closed without merging**
