### PR TITLE
 On branch master

### PR DESCRIPTION
**Pull request by camartinez04**
Chaging Updates into Patch to get rid of the lots of verbosity on Pod's logs.

 Changes to be committed:
	modified:   pkg/common-controller/snapshot_controller.go

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by ggriffiths** [comment]
@camartinez04 can you use JSON patching similar to work in this PR:
https://github.com/kubernetes-csi/external-snapshotter/pull/526/files

We found this type of patching to work the best for K8s CRDs

**Comment by ggriffiths** [comment]
Also, you'll need to fill out the CLA mentioned above.

**Comment by ggriffiths** [comment]
@camartinez04, as discussed offline, please refactor the PR to work similar to how this work was done in #526.

Also, please update the PR title and fill out the PR description questions.

**Comment by xing-yang** [comment]
Hi @camartinez04, are you still working on this issue?

**Comment by ggriffiths** [comment]
Discussed this with Carlos, we'll see if anyone else has the bandwidth to do this work.

**Pull request closed without merging**
