### PR TITLE
Fix logging in the volumegroupsnapshot methods

### PR DESCRIPTION
**Pull request by Madhu-1**
Fix logging in the volumegroupsnapshot methods and also use `GroupSnapshotDeleteError` event type for delete volumegroupsnapshot failures

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup

> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Review by nixpanic — COMMENTED** [review]
/lgtm

**Comment by xing-yang** [comment]
1.29 test failure is tracked here: https://github.com/kubernetes-csi/csi-release-tools/issues/248

**Pull request merged**
