### PR TITLE
external-snapshotter should use CSI connection lib

### PR DESCRIPTION
**Pull request by andrewsykim**
/assign @msau42 @jsafrane @vladimirvivien 

Updating CSI sidecars to use the common connection library in csi-lib-utils.

### CODE REVIEW

**Comment by msau42** [comment]
We may need a followup PR similar to https://github.com/kubernetes-csi/external-provisioner/pull/230 in order to use a different connection timeout for the operations

**Comment by andrewsykim** [comment]
Noted, I also forgot to remove usage of connection timeout in a few places, I'll follow up :)

**Pull request merged**
