### PR TITLE
add leader election for snapshotter

### PR DESCRIPTION
**Pull request by wackxu**
/assign @xing-yang @jingxu97

### CODE REVIEW

**Comment by wackxu** [comment]
@xing-yang Sorry for the delay, updated

**Comment by wackxu** [comment]
@xing-yang @jingxu97 Can you take a look at this?

**Comment by xing-yang** [comment]
@msau42 Please take a look.  Thanks.

**Comment by wackxu** [comment]
@xing-yang @jingxu97 Can you take a look at this?

**Comment by xing-yang** [comment]
There is ongoing work to use "lease" instead of "events" for leader election in the provisioner.  We want to see how that is going and adopt the same approach.  We can revisit this after the K8S 1.13 release.

**Comment by xing-yang** [comment]
Leader election is added by this PR: https://github.com/kubernetes-csi/external-snapshotter/pull/107.  So I'm going to close this PR.
Thanks @wackxu for working on it!

**Pull request closed without merging**
