### PR TITLE
cherry-pick #293: revamp find content logic to fix 290 291 292

### PR DESCRIPTION
**Pull request by yuxiangqian**
(cherry picked from commit 45324b7a676d31a796aa64d9660e7a0861286c0c)

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #293  

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
cherry-pick from #293 

This PR fixes the following issues in snapshot controller in release branch 2.1:
Issue #290 : Disallow a pre-provisioned VolumeSnapshot pointing to a dynamically created VolumeSnapshotContent
Issue #291 : Verify VolumeSnapshot and VolumeSnapshotContent are bi-directional bound before initializing a deletion on a VolumeSnapshotContent which the to-be-deleted VolumeSnapshot points to.
Issue #292 : Allow deletion of a VolumeSnapshot/VolumeSnapshotContent when the VolumeSnapshotContent's DeletionPolicy
```

### CODE REVIEW

**Comment by xing-yang** [comment]
@yuxiangqian can you add a line in the release note stating that this is a cherry pick and referencing the original PR number?

**Comment by yuxiangqian** [comment]
> @yuxiangqian can you add a line in the release note stating that this is a cherry pick and referencing the original PR number?
done

**Pull request merged**
