### PR TITLE
Cherry pick of #287: Updated sidecar to not require VolumeSnapshotClass for snapshot deletion

### PR DESCRIPTION
**Pull request by ialidzhikov**
/kind bug

Cherry pick of #287 on release-2.1.

#287: Updated sidecar to not require VolumeSnapshotClass for snapshot deletion 

**Which issue(s) this PR fixes**:

Ref #306

**Does this PR introduce a user-facing change?**:

```release-note
Cherry pick of #287: Allows the sidecar to delete volume snapshots if the volume snapshot class is not found.
```

### CODE REVIEW

**Review by rfranzke — APPROVED** [review]

**Comment by ialidzhikov** [comment]
@xing-yang , pull-kubernetes-csi-external-snapshotter-1-20-on-kubernetes-1-20 fails to clone v1.20.0 of kubernetes/kubernetes. I don’t think that it is something related to this PR.

**Comment by ialidzhikov** [comment]
@xing-yang , I believe the job configuration is wrong.

It currently tries to clone 1.20.0 but there is no such tag. It should be v1.20.0.

```diff
-git clone --single-branch --branch 1.20.0 https://github.com/kubernetes/kubernetes /tmp/kubernetes
+git clone --single-branch --branch v1.20.0 https://github.com/kubernetes/kubernetes /tmp/kubernetes
```

Where lives the configuration this job?

**Comment by xing-yang** [comment]
@pohly any idea why "v" is missing from "v1.20.0" for this backport?  It is there for PRs running in master branch.

**Comment by xing-yang** [comment]
I see a difference between the two:

https://github.com/kubernetes-csi/external-snapshotter/blob/release-2.1/release-tools/prow.sh#L573
https://github.com/kubernetes-csi/external-snapshotter/blob/master/release-tools/prow.sh#L575

**Comment by ialidzhikov** [comment]
> I see a difference between the two:
> 
> https://github.com/kubernetes-csi/external-snapshotter/blob/release-2.1/release-tools/prow.sh#L573
> https://github.com/kubernetes-csi/external-snapshotter/blob/master/release-tools/prow.sh#L575
> 
> https://github.com/kubernetes-csi/external-snapshotter/blob/master/release-tools/prow.sh#L68-L78

See https://github.com/kubernetes-csi/external-snapshotter/pull/464/files ->  `version_to_git` func. I believe somewhere in https://github.com/kubernetes-csi/external-snapshotter/pull/464/files there is a fix for the failing git clone in `pull-kubernetes-csi-external-snapshotter-1-20-on-kubernetes-1-20`..

**Comment by xing-yang** [comment]
I think you can submit a separate PR just to add that version_to_git logic in release-2.1. 

CC @pohly @mattcary

**Comment by ialidzhikov** [comment]
The PR was based on old revision from `release-2.1` branch. I rebased it to latest `release-2.1` but it failed with the same error. @xing-yang , I have locally a change that can fix the `git clone` for `pull-kubernetes-csi-external-snapshotter-1-20-on-kubernetes-1-20 `. Should I create a PR with it to tackle this issue or? I see that this job/check is not labelled as required.

**Comment by xing-yang** [comment]
We can't merge a PR that can't pass a CI.

**Comment by ialidzhikov** [comment]
@xing-yang , I create https://github.com/kubernetes/test-infra/pull/20792 which should address the issue with the K8s 1.20 tests that should not be executed against `external-snapshotter@release-2.1`.

**Comment by pohly** [comment]
> We can't merge a PR that can't pass a CI.

1-20-on-kubernetes-1-20 is intentionally not required to pass at this time, therefore you can merge PRs even when it is failing.

**Review by vpnachev — APPROVED** [review]
/lgtm

**Pull request merged**
