### PR TITLE
Fix for CVE go-2023-1571

### PR DESCRIPTION
**Pull request by shubhamrajvanshi**
**What type of PR is this?**
/kind security
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Fixes https://pkg.go.dev/vuln/GO-2023-1571
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
This should help merge https://github.com/kubernetes-csi/external-snapshotter/pull/811 as mentioned [here](https://github.com/kubernetes-csi/external-snapshotter/pull/811#issuecomment-1446421355)
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xing-yang** [comment]
@shubhamrajvanshi can you cherry-pick this PR to release-6.2 branch?

**Comment by shubhamrajvanshi** [comment]
I have created the PR but can't add you over there as reviewer https://github.com/kubernetes-csi/external-snapshotter/pull/816

**Comment by andyzhangx** [comment]
> @andyzhangx: #815 failed to apply on top of branch "release-5.0":
> 
> ```
> Applying: updated go module files
> Using index info to reconstruct a base tree...
> M	go.mod
> M	go.sum
> Falling back to patching base and 3-way merge...
> Auto-merging go.sum
> CONFLICT (content): Merge conflict in go.sum
> Auto-merging go.mod
> CONFLICT (content): Merge conflict in go.mod
> error: Failed to merge in the changes.
> hint: Use 'git am --show-current-patch=diff' to see the failed patch
> Patch failed at 0001 updated go module files
> When you have resolved this problem, run "git am --continue".
> If you prefer to skip this patch, run "git am --skip" instead.
> To restore the original branch and stop patching, run "git am --abort".
> ```

@xing-yang this could approve the cherrypick bot works on current repo, I will add cherrypick bot for other csi driver repo.

**Pull request merged**
