### PR TITLE
Add options to configure leader election in snapshot-controller

### PR DESCRIPTION
**Pull request by bertinatto**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

This PR adds CLI arguments to configure leader election options in the snapshot-controller.

This was missed in PR #538.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
Add command line arguments to configure leader election options for the snapshot controller.
```

### CODE REVIEW

**Comment by bertinatto** [comment]
/test pull-kubernetes-csi-external-snapshotter-1-21-on-kubernetes-1-21
The failure doesn't seem related to this change.

**Comment by ggriffiths** [comment]
@bertinatto can you add a release note explaining that support for these three flags is being added? 

re: the defaults, yeah these seem to be the package-level defaults, so we should be good.
https://github.com/kubernetes-csi/csi-lib-utils/blob/f9b3af56d1f16431977b9e3387a52f13687513f8/leaderelection/leader_election.go#L40-L42

**Comment by bertinatto** [comment]
> @bertinatto can you add a release note explaining that support for these three flags is being added?
> 
> re: the defaults, yeah these seem to be the package-level defaults, so we should be good.
> https://github.com/kubernetes-csi/csi-lib-utils/blob/f9b3af56d1f16431977b9e3387a52f13687513f8/leaderelection/leader_election.go#L40-L42

@ggriffiths PR #538 added the following note, which I believe should cover this:

`Add command line arguments to configure leader election options`

**Comment by xing-yang** [comment]
@bertinatto, can you add that to the release note of this PR?  We need that when drafting release note for the next release.

**Comment by bertinatto** [comment]
> @bertinatto, can you add this to the release note of this PR? We need this when drafting release note for the next release.
> 
> ```
> Add command line arguments to configure leader election options for the snapshot controller.
> ```

Sure, done!

**Pull request merged**
