### PR TITLE
change snapshot controller image version to 6.2.1 in release-6.2 branch

### PR DESCRIPTION
**Pull request by Jainbrt**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change

/kind bug

> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Cherrypick #809: Change snapshot controller image version to 6.2.1
```

### CODE REVIEW

**Comment by Jainbrt** [comment]
@xing-yang would you be able to help to get through the trivy scanner failure ?

**Comment by xing-yang** [comment]
We'll have to submit a PR to resolve the CVEs in order to pass the Trivy scanner.  This lib golang.org/x/net needs to be updated to a newer version.

**Comment by Jainbrt** [comment]
Thanks @xing-yang for responding. would you suggest to raise a new PR for CVEs?

**Comment by xing-yang** [comment]
> Thanks @xing-yang for responding. would you suggest to raise a new PR for CVEs?

@Jainbrt Yes, can you help raise a separate PR to fix the CVEs?

**Comment by shubhamrajvanshi** [comment]
> > Thanks @xing-yang for responding. would you suggest to raise a new PR for CVEs?
> 
> @Jainbrt Yes, can you help raise a separate PR to fix the CVEs?
Created a PR for this https://github.com/kubernetes-csi/external-snapshotter/pull/815. 
I hope we can get this PR merged quickly now

**Comment by xing-yang** [comment]
You probably need to do a rebase.

**Comment by xing-yang** [comment]
Can you squash your commits?

**Pull request closed without merging**
