### PR TITLE
Cherry-picks of #409 and #439: Adding --http-endpoint to snapshot components

### PR DESCRIPTION
**Pull request by chrishenzie**
**What type of PR is this?**
> /kind feature

**What this PR does / why we need it**:
This PR contains cherry-picks of #409 and #439, which each provide an `--http-endpoint` flag for the snapshot-controller and csi-snapshotter.

This is already present in v4; backporting so v3 users can make use of leader election health checks and have a consistent `--http-endpoint` flag across the snapshot-controller and csi-snapshotter.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xing-yang** [comment]
We don't backport new features to stable release branches.

**Comment by chrishenzie** [comment]
I see, is the target branch incorrect? What would be the best way to bring this feature into v3, or are you suggesting this is not possible at all?

**Comment by msau42** [comment]
@xing-yang in this case, leader-election check is a bug fix, and metrics should have been a beta requirement. Although I agree the snapshot-controller changes are very big so it is risky to put in a patch release. Should we consider making a new v3 minor release?

**Comment by xing-yang** [comment]
> @xing-yang in this case, leader-election check is a bug fix, and metrics should have been a beta requirement. Although I agree the snapshot-controller changes are very big so it is risky to put in a patch release. Should we consider making a new v3 minor release?

We always cut minor release directly from master though.  In this case, 4.0 is already out so we can't cut from master any more.

**Comment by msau42** [comment]
We could potentially cut from head of release-3.0

**Comment by xing-yang** [comment]
Issue opened here for discussions: https://github.com/kubernetes-csi/docs/issues/419

**Comment by verult** [comment]
Gentle ping! I realized that the `reset_timestamp` fix for the CSI controller metrics `csi_sidecar_operation_seconds` is in csi-lib-utils 0.9.0, so snapshot operation metrics are broken in 3.x.

**Comment by xing-yang** [comment]
I think we are trying to wrap up discussions in the following PR.  Once we're okay with that, we can make this change in the 3.1.0 release.
https://github.com/kubernetes-csi/docs/pull/423/

**Comment by chrishenzie** [comment]
@xing-yang Ready for merge on this PR

**Comment by xing-yang** [comment]
@chrishenzie We can't merge this as this is a backport to release-3.0.  We need to cut a branch for release-3.1 first and then add this change there.

I'll be out for a few hours.  I'll cut a release-3.1 branch when I'm back.

**Comment by xing-yang** [comment]
@chrishenzie A new branch `release-3.1` is cut from `release-3.0`.
https://github.com/kubernetes-csi/external-snapshotter/tree/release-3.1

Can you close this PR and backport the changes to `release-3.1`?

**Comment by chrishenzie** [comment]
/close

@xing-yang Done, opened https://github.com/kubernetes-csi/external-snapshotter/pull/511 for this work

**Pull request closed without merging**
