### PR TITLE
add pvcLister to snapshot controller

### PR DESCRIPTION
**Pull request by wackxu**
fix https://github.com/kubernetes-csi/external-snapshotter/issues/70
@xing-yang @jingxu97

### CODE REVIEW

**Comment by xing-yang** [comment]
/lgtm

Thanks for the fix!

**Comment by xing-yang** [comment]
@wackxu This PR was merged earlier but caused a hang when creating a snapshot.  So I had to revert it.  Please fix the problem and re-submit.  Thanks.

**Comment by xing-yang** [comment]
@wackxu When fixing this issue, please also add a unit test to catch this hang.  Thanks.

**Comment by wackxu** [comment]
@xing-yang Sorry for that, will take a look.

**Pull request merged**
