### PR TITLE
Remove unwanted code conditions

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by yuxiangqian** [comment]
thanks @humblec , could you rebase?

**Comment by humblec** [comment]
> thanks @humblec , could you rebase?

@yuxiangqian @xing-yang done.. ptal. :+1:

**Comment by humblec** [comment]
/me checking on why test is failing.

**Comment by xing-yang** [comment]
@humblec do you still want to hold this?

**Comment by humblec** [comment]
> @humblec do you still want to hold this?

@xing-yang no.. this is good to go !! Thanks!

**Pull request merged**
