### PR TITLE
Add groupName in doc.go when generating files

### LINKED ISSUE #112: Missing 'groupName' comment in doc.go - wrong group for fake objects
The group name of the APIs is "snapshot.storage.k8s.io" as specified here:

https://github.com/kubernetes-csi/external-snapshotter/blob/master/pkg/apis/volumesnapshot/v1alpha1/register.go#L23

However, "fake" objects are generated with "volumesnapshot"

https://github.com/kubernetes-csi/external-snapshotter/blob/master/pkg/client/clientset/versioned/typed/volumesnapshot/v1alpha1/fake/fake_volumesnapshot.go#L37

It seems that doc.go is missing the comment 
`
// +groupName=snapshot.storage.k8s.io
`

Due to this issue, we cannot use fake entities to do unit tests.

### PR DESCRIPTION
**Pull request by xing-yang**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Adds groupName in doc.go when generating files so that the fake volumesnapshot has the correct groupName.

**Which issue(s) this PR fixes**:
Fixes #112

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Changes the API group name for the fake VolumeSnapshot object to "snapshot.storage.k8s.io" to be in-sync with the group name of the real VolumeSnapshot object. As a result, the generated interfaces for clientset and informers of VolumeSnapshot are also changed from "VolumeSnapshot" to "Snapshot".
```

### CODE REVIEW

**Comment by xing-yang** [comment]
@msau42 @j-griffith PTAL.  Thanks.

**Comment by msau42** [comment]
Is this a breaking change? Do we need a release note?

**Comment by xing-yang** [comment]
There is no API change here, so I initially thought release note is not needed. However, if someone uses informers and clientset of volumesnapshot directly, they will have to change their code.  So let me add a release note for that.

**Comment by msau42** [comment]
Also the group name is changing right?

**Comment by xing-yang** [comment]
The group name is only changed for the fake object which can be used for testing (to make sure they are in-sync with the real group name).  The group name for the real VolumeSnapshot object remains the same.  To my surprise, this also changes "VolumeSnapshot" to "Snapshot" when referencing the objects in the clientset and informers.

**Pull request merged**
