### PR TITLE
Re-enable k8s e2e tests in pull jobs

### PR DESCRIPTION
**Pull request by msau42**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
snapshotter pull jobs were misleading and not actually running the k8s e2e tests.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by msau42** [comment]
@xing-yang @ggriffiths I think there are some problems with the way rbac rules are installed. Can you take a look?

**Comment by ggriffiths** [comment]
> @xing-yang @ggriffiths I think there are some problems with the way rbac rules are installed. Can you take a look?

Yes, taking a look now.

**Comment by ggriffiths** [comment]
@msau42 @xing-yang I have two PRs open to fix these tests:
1. Fix for RBAC version: https://github.com/kubernetes-csi/csi-release-tools/pull/78
2. With the above fix, k8s 1.16 was still failing to deploy the hostpath driver. This fixes that problem:
https://github.com/kubernetes-csi/csi-driver-host-path/pull/174  

Both fixes are tested together in this PR (with your change from this PR)
https://github.com/kubernetes-csi/external-snapshotter/pull/299

**Pull request merged**
