### PR TITLE
add dep prune options and remove unused packages

### PR DESCRIPTION
**Pull request by msau42**
I ran "dep ensure".

I did not run "dep ensure -update".

### CODE REVIEW

**Comment by msau42** [comment]
Only adding prune options.  Will look into removing constraints and updating vendor separately

**Comment by jingxu97** [comment]
I manually test the PR, and it works.

**Comment by xing-yang** [comment]
I ran "dep ensure" on this PR.  It seems to be fine.  This change is actually already included in this PR: https://github.com/kubernetes-csi/external-snapshotter/pull/88.  However, #88 has not been updated for a while.  So I'm fine getting this one merged first.  Then #88 can be rebased to include klog changes only.

**Pull request merged**
