### PR TITLE
Do input validation before creating CRD

### PR DESCRIPTION
**Pull request by Madhu-1**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

   /kind cleanup

> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

do snapshotnameprefix validation before creating the CRD. this will help us to catch the invalid CLI args ASAP.

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Comment by xing-yang** [comment]
@Madhu-1 Can you answer the question "what type of PR is this?"?  I think this is "/kind cleanup".

**Comment by Madhu-1** [comment]
@xing-yang yes its a cleanup. updated Thanks

**Comment by lpabon** [comment]
@Madhu-1 How can this ever be length of zero if the default value of the flag is `snapshot`?

**Comment by Madhu-1** [comment]
> @Madhu-1 How can this ever be length of zero if the default value of the flag is `snapshot`?
> 
> See https://github.com/kubernetes-csi/external-snapshotter/blob/master/cmd/csi-snapshotter/main.go#L67

I just moved the check above. maybe this can be set to empty by the user?

**Comment by lpabon** [comment]
> I just moved the check above. maybe this can be set to empty by the user?
True, but the likely of this happening is really low, in my opinion.

**Pull request closed without merging**
