### PR TITLE
Fix the requeue logic

### PR DESCRIPTION
**Pull request by xing-yang**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Add requeue to the sidecar controller.

**Which issue(s) this PR fixes**:
Part of #225

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
This fixes the re-queue logic so a failed snapshot operation will be added back to a rate limited queue for retries.
```

### CODE REVIEW

**Comment by humblec** [comment]
unless I missed something the logic here looks good to me.  However we will wait for @bswartz as the issue is reproducible in the setup and can have some real validation. considering this is on cache and sync code path, its better to get validated.

**Comment by bswartz** [comment]
I downloaded this patch and ran it in my torture tests and I don't see a single slow snapshot anymore. Unfortunately my torture test eventually crashed after 35 snapshots due to bugs in other components, but I am confident that this patch solves my problem.

Thanks @xing-yang !

**Comment by xing-yang** [comment]
Thanks @bswartz for testing this!

**Comment by bswartz** [comment]
Okay I fixed the bug in my torture test, and re-ran it with this patch. I got up to 278 snapshots with no hangs and no crashes, before I decided to end the test.

**Comment by xing-yang** [comment]
That's awesome.  Thanks @bswartz!

**Pull request merged**
