### PR TITLE
Cherry pick of #298, #301: Re-enable k8s e2e tests

### PR DESCRIPTION
**Pull request by msau42**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Cherry-pick of https://github.com/kubernetes-csi/external-snapshotter/pull/301 and https://github.com/kubernetes-csi/external-snapshotter/pull/298

Updates csi-release-tools to latest to pick up snapshotter e2e fixes, and re-enable k8s e2e tests.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xing-yang** [comment]
Can you add a note at the top that this is a cherry pick and link to the original PR?

**Comment by msau42** [comment]
done

**Comment by msau42** [comment]
whoops i pushed 2nd cherry pick too early. I guess we can combine both into one pr

**Pull request merged**
