### PR TITLE
Small fixes to snapshot-controller YAML

### PR DESCRIPTION
**Pull request by bswartz**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Remove "sidecar" language for the controller.
Update image tag to 2.0.0-rc4 (the latest)

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by xing-yang** [comment]
Please also change the csi-snapshotter image to rc4.  Also change the imagePullPolicy for both csi-snapshotter and snapshot-controller from "IfNotPresent" to "Always".

**Comment by bswartz** [comment]
> Please also change the csi-snapshotter image to rc4. Also change the imagePullPolicy for both csi-snapshotter and snapshot-controller from "IfNotPresent" to "Always".

Why change the imagePullPolicy? IMO, always pulling is wasteful of resources (and slows down the system) and only makes sense when using an image tag that will be recycled (like latest/canary, but not 2.0.0-rc4).

**Comment by xing-yang** [comment]
> Why change the imagePullPolicy? IMO, always pulling is wasteful of resources (and slows down the system) and only makes sense when using an image tag that will be recycled (like latest/canary, but not 2.0.0-rc4).

This is to be consistent with other image pulling policies.  I changed it from "Always" to "IfNotPresent" during testing and forgot to change it back.  This is to make sure the image is always cleanly downloaded from the official repo.  You are change it to "IfNotPresent" during your testing, but the checked-in version should be "Always".

**Pull request merged**
